### ISSUE TITLE
Page 198 links to missing resource

### ISSUE THREAD

**Issue by Bo0mer** [jamtur01/aom-code#4]
Hi,

Describing the `carbon.conf` file on page 198 links to https://github.com/jamtur01/aom-code/blob/master/code/4/graphite/carbon.conf, which returns 404.

```text
“Let's look at our carbon.conf configuration file now. 
It's a bit big so we're going to break it into pieces to review. 
You can find the full file in the book's source code on GitHub.”

Excerpt From: James Turnbull. “The Art of Monitoring.” 
```

The correct link should be https://github.com/jamtur01/aom-code/blob/master/4/graphite/carbon.conf.

-Ivan

**Comment by jamtur01** [comment]
This is fixed in the latest release. Thanks.
